<?php

#	Для номеров id записей в таблице weather_nebo,
#	соотв. состояниям погоды и картинкам разным:
#	+----+----------------------------+
#	| id | name                       |
#	+----+----------------------------+
#	|  1 | Ясно                       |* 1
#	|  2 | Облачно                    |* 3
#	|  3 | Дожди                      |* 5
#	|  4 | Снег                       |* 7
#	|  5 | Переменная облачность      |* 4
#	|  6 | Пасмурно                   |* 3
#	|  7 | Снегопад                   |* 9
#	|  8 | Небольшой снег             |* 10
#	|  9 | Густой туман               |* 16
#	| 10 | Легкий туман               |* 16
#	| 11 | Грозы                      |* 13
#	| 12 | Местами дожди              |* 11
#	| 13 | Туман                      |* 16
#	| 14 | Ледяная изморось           |* 17
#	| 15 | Снег с дождем              |* 17
#	| 16 | Повышенная влажность       |* 12
#	| 17 | Изморось                   |* 17
#	| 18 | Град с дождем              |* 15
#	| 19 | Ветрено                    |* 18
#	| 20 | Преимущественно безоблачно |* 4
#	| 21 | Туман                      |* 16
#	| 22 | Кратковременные дожди      |* 6
#	| 23 | Возможны грозы             |* 13
#	+----+----------------------------+

	return array(
		'Fair' => 1,
		'Fair/Windy' => 1,
		'Widespread Dust' => 1,    # типа ветренно, пыльно
		'Widespread Dust/Windy' => 1,    # типа ветренно, пыльно
		'Blowing Dust' => 1,
		'Blowing Dust/Windy' => 1,
		'Wind Early' => 1,
		'Wind Late' => 1,
		'Sand' => 1,    # типа пыльно
		'Sand/Windy' => 1,    # типа пыльно
		'Sandstorm' => 1,    # типа пыльно
		'AM Sun' => 1,
		'PM Sun' => 1,
		'Sun' => 1,
		'Sunny' => 1,
		'Sunny/Wind' => 1,
		'Sunny/Windy' => 1,
		'Mostly Sunny'=> 1,
		'M Sunny'=> 1,
		'Mostly Sunny/Wind'=> 1,
		'Wind' => 1,
		'Clear' => 1,
		'Clear/Wind' => 1,
		'Clear/Windy' => 1,
		'Clearing Early' => 1,
		'Clearing Late' => 1,
		'Cloudy' => 2,
		'Rain and Snow' => 3,
		'Rain/Snow/Wind' => 3,
		'Rain' => 3,
		'PM Rain' => 3,
		'AM Rain' => 3,
		'Light Rain' => 23,
		'Light Rain/Windy' => 23,
		'PM Light Rain/Wind' => 23,
		'Light Rain/Windy/Fog' => 23,
		'Light Rain Shower/Windy' => 23,
		'Rain Shower/Windy' => 3,
		'Light Drizzle/Windy'=> 3,
		'Drizzle/Windy'=> 3,
		'Light Freezing Rain/Sleet' => 3,
		'Light Freezing Rain/Windy' => 3,
		'Light Freezing Rain/Fog' => 3,
		'Freezing Rain/Fog' => 3,
		'Sleet and Freezing Rain' => 3,
		'Freezing Rain/Windy' => 3,
		'Rain/Freezing Rain/Windy' => 3,
		'Rain/Windy' => 3,
		'Heavy Rain/Windy' => 3,
		'Heavy Rain Shower/Windy' => 3,
		'Heavy Rain Shower' => 3,
		'Light Rain/Fog' => 3,
		'Rain/Fog' => 3,
		'AM Light Rain' => 3,
		'PM Light Rain' => 3,
		'Thundershowers' => 3,
		'T-showers' => 3,
		'Heavy Rain' => 3,
		'Rain/Wind' => 3,
		'Heavy Rain/Wind' => 3,
		'Scattered Flurries' => 3,
		'Rain/Ice' => 3,
		'AM Rain/Ice' => 3,
		'PM Rain/Ice' => 3,
		'Showers/Wind' => 3,
		'Snow' => 4,
		'PM Snow' => 4,
		'AM Snow' => 4,
		'Blowing Snow' => 4, #Выдувание снега
		'Scattered Snow Showers' => 4,
		'Snow Late' => 4,
		'Snow/Wind' => 4,
		'Snow/Fog' => 4,
		'Snow/Windy' => 4,
		'Heavy Snow Shower' => 4,
		'Heavy Snow/Windy' => 4,
		'Heavy Snow Shower/Windy' => 4,
		'AM Snow/Wind' => 4,
		'PM Snow/Wind' => 4,
		'Snow to Ice' => 4,
		'Ice Crystals' => 4,
		'Ice Crystals/Fog' => 4,
		'Clouds Early/Clearing' => 5,
		'Clouds Early/Clearing Late' => 5,
		'AM Clouds/PM Sun' => 5,
		'AM Clouds<br>PM Sun' => 5,
		'Partly Cloudy' => 5,
		'P Cloudy' => 5,
		'Partly Cloudy/Wind' => 5,
		'Partly Cloudy/Windy' => 5,
		'Mist' => 13,
		'Mostly Cloudy' => 6,
		'M Cloudy' => 6,
		'Mostly Cloudy/Wind' => 6,
		'Mostly Cloudy/Windy' => 6,
		'Cloudy/Windy' => 2,
		'Cloudy/Wind' => 2,
		'AM Cloudy/Wind' => 10,
		'PM Cloudy/Wind' => 10,
		'Blizzard' => 7,
		'Snow Pellets' => 7,
		'Drifting Snow' => 7,
		'Heavy Snow' => 7,
		'Snow Showers' => 7,
		'Snow Shower' => 7,
		'Snow Grains' => 7,
		'Light Snow Grains' => 7,
		'Light Snow/Windy' => 7,
		'AM Snow Showers' => 7,
		'PM Snow Showers' => 7,
		'Snow Showers Early' => 7,
		'Snow Showers Late' => 7,
		'Snow Showers/Wind' => 7,
		'Snow Shower/Windy' => 7,
		'AM Snow Showers/Wind' => 7,
		'PM Snow Showers/Wind' => 7,
		'Flurries' => 7, #Снегопады(ливни)
		'Snow Showers/Wind Early' => 8,
		'Fluries' => 8,
		'Flurries/Wind' => 8,
		'Light Snow' => 8,
		'Light Snow/Fog' => 8,
		'Light Snow Shower/Windy' => 8,
		'Light Snow Grains/Windy' => 8,
		'AM Light Snow' => 9,
		'PM Light Snow' => 9,
		'Light Snow/Wind' => 8,
		'AM Light Snow/Wind' => 8,
		'PM Light Snow/Wind' => 8,
		'Light Snow Early' => 9,
		'Light Snow Late' => 9,
		'Light Snow Shower' => 8,
		'Few Snow Showers' => 8,
		'Few Snow Showers/Wind' => 8,
		'Blowing Snow/Windy' => 8,
		'Fog' => 13,
		'Haze' => 13,
		'Thunder in the Vicinity' => 11, # местами грозы
		'Thunderstorm' => 11,
		'Thunderstorm/Windy' => 11,
		'Scattered Thunderstorms/Wind' => 11,
		'Thunderstorms' => 11,
		'PM Thunderstorms' => 11,
		'AM Thunderstorms' => 11,
		'Thunderstorms Late' => 11,
		'Isolated Thunderstorms' => 11,
		'Scattered Thunderstorms' => 11,
		'Thunderstorms Early' => 11,
		'PM Thundershowers' => 12,
		'AM Thundershowers' => 12,
		'T-storms' => 11,
		'PM T-storms' => 11,
		'AM T-storms' => 11,
		'Scattered T-storms' => 11,
		'Isolated T-storms' => 11,
		'T-storms Late' => 11,
		'T-storms Early' => 11,
		'Showers' => 12,
		'AM Showers' => 12,
		'AM Showers/Wind' => 12,
		'PM Showers' => 12,
		'PM Showers/Wind' => 12,
		'Smoke' => 13,
		'Shallow Fog' => 13,
		'Partial Fog' => 13,
		'Fog/Windy' => 13,
		'Freezing Drizzle' => 14,
		'Light Freezing Rain' => 14,
		'Freezing Drizzle/Fog' => 14,
		'Light Rain/Freezing Rain' => 14,
		'Ice to Rain' => 18,
		'Rain/Freezing Rain' => 14,
		'AM Ice' => 14,
		'PM Ice' => 14,
		'Ice' => 14,
		'Mixed Snow, Rain' => 15,
		'Mixed Rain And Snow' => 15,
		'Light Snow/Freezing Rain' => 15,
		'Snow/Freezing Rain' => 15,
		'Wintry Mix' => 15,
		'Wintry Mix us' => 15,
		'Rain/Snow' => 15,
		'Rain and Sleet' => 15,
		'AM Rain/Snow' => 15,
		'PM Rain/Snow' => 15,
		'Rain/Snow Showers' => 15,
		'R/S Showers' => 15,
		'AM Rain/Snow Showers' => 15,
		'PM Rain/Snow Showers' => 15,
		'Snow to Rain' => 15,
		'Snow/Freezing Rain' => 15,
		'AM Snow to Rain' => 15,
		'PM Snow to Rain' => 15,
		'Rain to Snow' => 15,
		'Light Sleet' => 15,
		'AM Rain to Snow' => 15,
		'PM Rain to Snow' => 15,
		'Rain/Snow Showers Early' => 15,
		'Rain/Snow Showers Late' => 15,
		'Snow to Rain/Wind' => 15,
		'Snow to Wintry Mix' => 15,
		'Rain/Snow Showers/Wind' => 15,
		'AM Rain/Snow Showers/Wind' => 15,
		'Sleet' => 15,
		'Scattered Showers' => 22,
		'Scattered showers' =>  22,
		'Drizzle' => 17,
		'Light Drizzle' => 17,
		'Freezing Rain' => 18,
		'Windy'    => 19,
		'Wintry Mix/Wind' => 19,
		'Thunder' => 19,
		'Drifting Snow/Windy' => 19,
		'Mostly Clear' => 20,
		'M Clear' => 20,
		'Hazy' => 13,
		'Foggy' => 13,
		'AM Fog/PM Clouds' => 13,
		'Few Showers' => 22,
		'Rain Shower' => 22,
		'Showers Late' => 22,
		'Showers Early' => 22,
		'Rain Early' => 22,
		'Rain Late' => 22,
		'Light Rain' =>22,
		'Light Freezing Drizzle' => 22,
		'Light Freezing Drizzle/Fog' => 22,
		'Sprinkles' => 22,
		'Light Rain Late' => 22,
		'Light Rain Early' => 22,
		'Light Rain/Wind' => 22,
		'Light Rain Shower' => 22,
		'Light Rain with Thunder' => 22,
		'Showers in the Vicinity' => 22,
		'Rain/Thunder' => 11,
		'Freezing Rain/Sleet' => 15,
		'Broken Clouds' => 5,
		'Few Clouds' => 5,
		'Overcast' => 6,
		'Scattered Clouds' => 5,
	);

?>